name: Auto Merge Dependabot PRs

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from dependabot
        if: contains(github.actor, 'dependabot[bot]')
        run: |
          echo "PR is from dependabot, checking if all checks have passed"
      - name: Check if all checks have passed
        if: github.event.pull_request.mergeable == 'true'
        run: |
          echo "All checks have passed, merging PR"
      - name: Merge PR
        if: github.event.pull_request.mergeable == 'true'
        run: |
          gh pr merge --auto --merge "${{github.event.pull_request.html_url}}"
