name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2.2.2
      with:
        python-version: "3.8"
    - name: Install poetry
      run: make poetry-download
    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry install
    - name: Run style checks
      run: make check-codestyle
    - name: Run tests
      run: make test
    - name: Run safety checks
      run: make check-safety
    - name: Report Coverage
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Python --force-language -r coverage.xml
