name: Documentation
on: [ push, workflow_dispatch ]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3
      - name: Set up Python 3.10
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Install dev-dependencies
        run: pip install toml && python -c 'import toml; c = toml.load("pyproject.toml");print("\n".join(c["tool"]["poetry"]["group"]["dev"]["dependencies"]))' | pip install -r /dev/stdin
      - name: Install async dependencies
        run: pip install toml && python -c 'import toml; c = toml.load("pyproject.toml");print("\n".join(c["tool"]["poetry"]["extras"]["async"]))' | pip install -r /dev/stdin
      - name: Build Documentation
        run: cd docs && make html && cd ..
      - name: Upload Documentation to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/_build/html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true
